/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Cuenta;
import Modelo.CuentaAhorro;
import Modelo.CuentaCorriente;
import ModeloDAO.CuentasDAO;
import Modelo.Persona;
import ModeloDAO.PersonaDAO;
import static Vistas.CuentasListadoFrm.cuenEditar;
import java.awt.event.ItemEvent;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CuentasFrame extends javax.swing.JFrame {

    /**
     * Creates new form CuentasFrame
     */
    private final List<Persona> list;
    public static boolean cuentaEdicion = false;
    
    public CuentasFrame() {
        initComponents();
         //Para que la forma salga en el centro
        this.setLocationRelativeTo(null);
        //Llenar el comboBox de los datos de los clientes
        String itemPersonaCmb = null;
        PersonaDAO perDAO = new PersonaDAO();
        list = perDAO.listarPersonas();
        Collections.sort(list);
        Iterator<Persona> iter = list.iterator();
        Persona per = null;
        
        CuentasListadoFrm cuentaLista = new CuentasListadoFrm();
        cuentaEdicion = cuentaLista.edicion;
        //JComboBox personasCB = new JComboBox((ComboBoxModel) list);
        
        if (cuentaLista.edicion == false) {
        while (iter.hasNext()) {
            
            per = iter.next();
            
           // itemPersonaCmb=per.getNombre();
            this.clientesCmbBox.addItem(per);
        } 
        }
        
        this.setLocationRelativeTo(null);
        
        cuentaEdicion = cuentaLista.edicion;
        if (cuentaLista.edicion) {
            CuentaAhorro cAhorro = new CuentaAhorro();
            CuentaCorriente cCorriente = new CuentaCorriente();
        //Se verifica que objeto se esta recibiendo en el método
            if (cuentaLista.cuenEditar instanceof CuentaAhorro) {
                CuentaAhorro avl = (CuentaAhorro) cuenEditar;
                this.titulo.setText("Actualizar Cliente");
                int numcuenta = avl.getNumerocuenta();
                this.numcuentaTxtFld.setText(String.valueOf(numcuenta));
                String tipoCuenta = "Ahorro";
                TipoCuentaCBox.setSelectedItem(tipoCuenta);
                double saldo = avl.getSaldo();
                Persona p = avl.getCliente();
                clientesCmbBox.addItem(p);
                System.out.println("p"+p);
                this.saldoTXTFld.setText(String.valueOf(saldo));
                double interes = avl.getInteres();
                interesTxtFld.setText(String.valueOf(interes));
                double saldomin = avl.getSaldomin();
                saldominTxtFld.setText(String.valueOf(saldomin));
        } else {
                CuentaCorriente avl = (CuentaCorriente) cuenEditar;
                this.titulo.setText("Actualizar Cliente");
                int numcuenta = avl.getNumerocuenta();
                this.numcuentaTxtFld.setText(String.valueOf(numcuenta));
                    String tipoCuenta = "Corriente";
                TipoCuentaCBox.setSelectedItem(tipoCuenta);
                double saldo = avl.getSaldo();
                this.saldoTXTFld.setText(String.valueOf(saldo));
                Persona p = avl.getCliente();
                clientesCmbBox.addItem(p);
                double interes = avl.getInteres();
                interesTxtFld.setText(String.valueOf(interes));
                String saldomin = "No aplica";
                saldominTxtFld.setText(String.valueOf(saldomin));
            }   
            this.CrearBtn.setText("Actualizar");
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numcuentaTxtFld = new javax.swing.JTextField();
        saldoTXTFld = new javax.swing.JTextField();
        clientesCmbBox = new javax.swing.JComboBox();
        TipoCuentaCBox = new javax.swing.JComboBox<>();
        interesTxtFld = new javax.swing.JTextField();
        saldominTxtFld = new javax.swing.JTextField();
        CrearBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        idClienteTxtF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailClienteTxtF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tipoIdCTxtF = new javax.swing.JTextField();
        nombreClienteTxtF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("Gestión de Cuentas");

        jLabel2.setText("Número de cuenta");

        jLabel3.setText("Saldo Inicial");

        jLabel4.setText("Seleccione el Cliente");

        jLabel5.setText("Tipo de Cuenta");

        jLabel6.setText("Interes");

        jLabel7.setText("Saldo mínimo");

        numcuentaTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcuentaTxtFldActionPerformed(evt);
            }
        });
        numcuentaTxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numcuentaTxtFldKeyTyped(evt);
            }
        });

        saldoTXTFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoTXTFldActionPerformed(evt);
            }
        });
        saldoTXTFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                saldoTXTFldKeyTyped(evt);
            }
        });

        clientesCmbBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clientesCmbBoxItemStateChanged(evt);
            }
        });
        clientesCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesCmbBoxActionPerformed(evt);
            }
        });

        TipoCuentaCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahorros", "Corriente" }));
        TipoCuentaCBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoCuentaCBoxItemStateChanged(evt);
            }
        });
        TipoCuentaCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCuentaCBoxActionPerformed(evt);
            }
        });

        interesTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interesTxtFldActionPerformed(evt);
            }
        });

        CrearBtn.setText("Crear");
        CrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");

        jButton3.setText("Salir");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Id");

        idClienteTxtF.setEnabled(false);

        jLabel10.setText("Tipo Id");

        jLabel11.setText("Nombre");

        emailClienteTxtF.setEnabled(false);
        emailClienteTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailClienteTxtFActionPerformed(evt);
            }
        });

        jLabel12.setText("Email");

        tipoIdCTxtF.setEnabled(false);

        nombreClienteTxtF.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreClienteTxtF, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(emailClienteTxtF)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idClienteTxtF, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(tipoIdCTxtF))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(idClienteTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tipoIdCTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nombreClienteTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(emailClienteTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel8.setText("Información del Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientesCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numcuentaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saldoTXTFld, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saldominTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(interesTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TipoCuentaCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(CrearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(79, 79, 79)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(titulo)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numcuentaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(saldoTXTFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clientesCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(saldominTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TipoCuentaCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(interesTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))
                                .addGap(102, 102, 102)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CrearBtn)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        clientesCmbBox.getAccessibleContext().setAccessibleName("");
        clientesCmbBox.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBtnActionPerformed
        // TODO add your handling code here:
        int idcuenta;
        double saldo;
        String tipocuenta;
        double interes;
        double saldomin;        
        try {
            idcuenta = Integer.parseInt(numcuentaTxtFld.getText());
            //Validar que sea un numero. Manejar el error
            //Mensajes por medio de ventanas emergentes 
            //y cambiar el foco de la forma
            saldo = Double.parseDouble(saldoTXTFld.getText());
            tipocuenta = (String) TipoCuentaCBox.getSelectedItem();
            Persona per = (Persona) clientesCmbBox.getSelectedItem();
            interes = Double.parseDouble(interesTxtFld.getText());
            saldomin = Double.parseDouble(saldominTxtFld.getText());

            if ("Ahorros".equals(tipocuenta)) {
                CuentaAhorro cuen = new CuentaAhorro(interes, saldomin, idcuenta, per);
                CuentasDAO cuenDAO = new CuentasDAO();
                cuen.setSaldo(saldo);
                if (!cuentaEdicion) {
                    cuenDAO.crearCuenta(cuen);
                    JOptionPane.showMessageDialog(null, "Registro guardado");
                } else {
                    cuenDAO.actualizarCuenta(cuen);
                    JOptionPane.showMessageDialog(null, "Registro actualizado");
                }
                saldoTXTFld.setText("");
                numcuentaTxtFld.setText("");
                    
                }
            else{
                CuentaCorriente cuen = new CuentaCorriente(idcuenta,per);
                CuentasDAO cuenDAO = new CuentasDAO();
                cuen.setSaldo(saldo);
                if (!cuentaEdicion) {
                    cuenDAO.crearCuenta(cuen);
                    JOptionPane.showMessageDialog(null, "Registro guardado");
                } else {
                    cuenDAO.actualizarCuenta(cuen);
                    JOptionPane.showMessageDialog(null, "Registro actualizado");
                }
                saldoTXTFld.setText("");
                numcuentaTxtFld.setText("");
            }
                
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error en los datos ingresados");
            numcuentaTxtFld.setText("");
            numcuentaTxtFld.requestFocus();
        }            
        
    }//GEN-LAST:event_CrearBtnActionPerformed

    private void emailClienteTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailClienteTxtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailClienteTxtFActionPerformed

    private void clientesCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesCmbBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clientesCmbBoxActionPerformed

    private void clientesCmbBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clientesCmbBoxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Persona per=(Persona) clientesCmbBox.getSelectedItem();
            idClienteTxtF.setText(String.valueOf(per.getId()));
            nombreClienteTxtF.setText(per.getNombre());
            emailClienteTxtF.setText(per.getEmail());
            tipoIdCTxtF.setText(per.getTipoid());
//            System.out.println(clientesCmbBox.getSelectedObjects().toString());
        }

    }//GEN-LAST:event_clientesCmbBoxItemStateChanged

    private void numcuentaTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcuentaTxtFldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_numcuentaTxtFldActionPerformed

    private void interesTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interesTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interesTxtFldActionPerformed

    private void saldoTXTFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoTXTFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoTXTFldActionPerformed

    private void TipoCuentaCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCuentaCBoxActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_TipoCuentaCBoxActionPerformed

    private void TipoCuentaCBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoCuentaCBoxItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TipoCuentaCBoxItemStateChanged

    private void numcuentaTxtFldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numcuentaTxtFldKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Los datos deben ser numéricos");
        }
    }//GEN-LAST:event_numcuentaTxtFldKeyTyped

    private void saldoTXTFldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saldoTXTFldKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Los datos deben ser numéricos");
        }
    }//GEN-LAST:event_saldoTXTFldKeyTyped


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearBtn;
    private javax.swing.JComboBox<String> TipoCuentaCBox;
    private javax.swing.JComboBox clientesCmbBox;
    private javax.swing.JTextField emailClienteTxtF;
    private javax.swing.JTextField idClienteTxtF;
    private javax.swing.JTextField interesTxtFld;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombreClienteTxtF;
    private javax.swing.JTextField numcuentaTxtFld;
    private javax.swing.JTextField saldoTXTFld;
    private javax.swing.JTextField saldominTxtFld;
    private javax.swing.JTextField tipoIdCTxtF;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
